service: mobilenetv2

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  timeout: 60

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:getObject
      Resource: "arn:aws:s3:::mobilenetv2/*"

  environment:
    S3_BUCKET: model-mobilenetv2
    MODEL_PATH: mobileNetV2.pt


custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - model/**

functions:
  classify_image:
    handler: handler.classify_image
    memorySize: 3008
    events:
      - http:
          path: classify
          method: post
          cors: true

plugins:
  - serverless-python-requirements
